---
- hosts: all
  become: true
  tasks:
    - apt:
        update_cache: yes
        name: 
          - python-setuptools
          - python3-pip

- hosts: jupyter
  become: true
  tasks:
    - pip:
        name: 
          - notebook
          - redis
    - copy: 
        src: notebook.service
        dest: /etc/systemd/system/notebook.service
        mode: 0755

    - systemd:
        daemon_reload: yes

    - service:
        name: notebook
        state: started
        enabled: yes

    - file:
        path: /notebooks
        state: directory